/*
  # 插入示例工具数据

  1. 插入示例工具
    - 涵盖所有分类
    - 包含完整的字段信息
    - 用于测试和演示
*/

-- 插入示例工具数据
INSERT INTO tools (
  name, 
  tagline, 
  description, 
  website_url, 
  logo_url, 
  categories, 
  features, 
  pricing, 
  featured, 
  upvotes, 
  views, 
  rating, 
  review_count
) VALUES 
(
  'StructuralGPT',
  '基于AI的结构设计助手，快速生成结构方案',
  'StructuralGPT 是一款革命性的AI驱动结构设计工具，专为土木工程师打造。它利用先进的机器学习算法和大量的工程数据，能够在几分钟内生成优化的结构设计方案。该工具不仅能够处理常规的建筑结构设计，还能应对复杂的工程挑战，如高层建筑、大跨度结构和特殊形状建筑的结构设计。',
  'https://structuralgpt.com',
  'https://images.pexels.com/photos/3862132/pexels-photo-3862132.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['AI结构设计'],
  ARRAY['参数化设计', 'AI优化', '自动化出图'],
  'Freemium',
  true,
  2340,
  15420,
  4.8,
  156
),
(
  'BIM智能建模',
  '利用AI技术自动生成BIM模型',
  '利用AI技术自动生成BIM模型，支持多种建筑类型的快速建模，大大提升建模效率。',
  'https://bimaimodeling.com',
  'https://images.pexels.com/photos/3862379/pexels-photo-3862379.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['BIM软件'],
  ARRAY['BIM集成', '自动化出图', '参数化设计'],
  'Paid',
  true,
  1890,
  12340,
  4.6,
  89
),
(
  '智能造价估算',
  '基于历史数据的工程造价快速估算',
  '基于历史数据和AI算法的工程造价快速估算工具，准确率达95%以上，为项目决策提供可靠依据。',
  'https://smartcostestimate.com',
  'https://images.pexels.com/photos/3862365/pexels-photo-3862365.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['效率工具'],
  ARRAY['成本估算', 'AI优化'],
  'Paid',
  true,
  3120,
  18760,
  4.7,
  203
),
(
  '施工进度AI',
  '智能项目管理工具，优化施工进度安排',
  '智能项目管理工具，通过AI分析优化施工进度安排和资源配置，提升项目管理效率。',
  'https://constructionai.com',
  'https://images.pexels.com/photos/3862130/pexels-photo-3862130.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['智能施工管理'],
  ARRAY['协同工作', '安全监控'],
  'Paid',
  true,
  1650,
  11230,
  4.5,
  127
),
(
  'CAD智能绘图',
  '基于自然语言的CAD绘图工具',
  '基于自然语言的CAD绘图工具，通过描述即可生成专业工程图纸，大大提升绘图效率。',
  'https://smartcad.com',
  'https://images.pexels.com/photos/3862385/pexels-photo-3862385.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['图纸处理'],
  ARRAY['自动化出图', '参数化设计'],
  'Free',
  false,
  1420,
  9870,
  4.4,
  94
),
(
  '材料检测AI',
  '利用计算机视觉进行材料质量检测',
  '利用计算机视觉技术进行材料质量检测和缺陷识别的智能工具，提升检测精度和效率。',
  'https://materialai.com',
  'https://images.pexels.com/photos/3862388/pexels-photo-3862388.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['岩土工程'],
  ARRAY['AI优化', '安全监控'],
  'Trial',
  false,
  1180,
  8450,
  4.6,
  78
),
(
  '项目协作平台',
  '专为土木工程项目设计的智能协作平台',
  '专为土木工程项目设计的智能协作平台，支持多方实时协作，提升团队工作效率。',
  'https://projectcollab.com',
  'https://images.pexels.com/photos/3862390/pexels-photo-3862390.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['项目管理'],
  ARRAY['协同工作', 'BIM集成'],
  'Freemium',
  false,
  1560,
  10230,
  4.5,
  112
),
(
  '工程资料管理',
  '智能化的工程文档和资料管理系统',
  '智能化的工程文档和资料管理系统，支持文档分类、检索和版本控制。',
  'https://docmanager.com',
  'https://images.pexels.com/photos/3862392/pexels-photo-3862392.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['资料管理'],
  ARRAY['协同工作'],
  'Paid',
  false,
  980,
  7650,
  4.3,
  65
),
(
  '地质勘探AI',
  '基于机器学习的地质数据分析工具',
  '基于机器学习的地质数据分析工具，提供精准的地质勘探报告和风险评估。',
  'https://geoai.com',
  'https://images.pexels.com/photos/3862394/pexels-photo-3862394.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['岩土工程'],
  ARRAY['AI优化', '参数化设计'],
  'Paid',
  false,
  756,
  6890,
  4.2,
  43
),
(
  '钢筋配筋优化',
  '智能钢筋配筋计算和优化工具',
  '智能钢筋配筋计算和优化工具，基于AI算法优化配筋方案，节约材料成本。',
  'https://rebaroptimizer.com',
  'https://images.pexels.com/photos/3862396/pexels-photo-3862396.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['AI结构设计'],
  ARRAY['参数化设计', 'AI优化', '成本估算'],
  'Trial',
  false,
  1234,
  8970,
  4.6,
  87
),
(
  '混凝土强度预测',
  '利用机器学习预测混凝土强度发展',
  '利用机器学习预测混凝土强度发展趋势，为施工质量控制提供科学依据。',
  'https://concretestrength.com',
  'https://images.pexels.com/photos/3862398/pexels-photo-3862398.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['岩土工程'],
  ARRAY['AI优化'],
  'Free',
  false,
  892,
  6540,
  4.4,
  56
),
(
  '施工安全监控',
  '基于计算机视觉的施工现场安全监控',
  '基于计算机视觉的施工现场安全监控系统，实时识别安全隐患，保障施工安全。',
  'https://safetyvision.com',
  'https://images.pexels.com/photos/3862400/pexels-photo-3862400.jpeg?auto=compress&cs=tinysrgb&w=200',
  ARRAY['智能施工管理'],
  ARRAY['安全监控', 'AI优化'],
  'Paid',
  false,
  1876,
  13450,
  4.7,
  134
);